### ISSUE TITLE
Output Results Too Simple with Custom Dataset & Inquiry About Radar Plots

### ISSUE THREAD

**Issue by InTheFuture7** [OdedH/textual-pca#1]
@OdedH Hello, Great job on your work! 

I'm using my own dataset (a few car images) and the output is quite simple:
```
avg phrase: side
principal phrases: ['white', 'front']
```
Could you clarify if I might be misunderstanding the dataset usage? 

By the way, the radar plots you generated look fantastic! Could you provide some guidance or example code for creating similar plots?

Thank you!

**Comment by OdedH** [comment]
Hey @InTheFuture7, thank you for taking interest in my work! It’s a bit challenging to provide specific guidance without seeing the dataset. You can experiment with the average phrase parameters in the code to see if that helps. Is the dataset small? Both of your features make sense when dealing with cars, whether the car is white or if the picture was taken from the front or not. For more principal phrases, try increasing the variance parameter—there’s an explanation for that in the article. For the radar plots, please take a look at `radar_plots.py'. :)
